name: Basic checks

on:
  pull_request:
  push:
    branches:
      - main
      - release-*
    tags-ignore: [ v.* ]

jobs:
  check-code-style:
    name: Check Code Style
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Compilation and binary-compatibility check
        run: sbt "verifyCodeStyle;+IntegrationTest/compile;mimaReportBinaryIssues"

  check-docs:
    name: Check Docs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Create all API docs for artifacts/website and all reference docs
        run: sbt "unidoc; docs/paradox"
