name: Integration test for Kubernetes API with Maven

on:
  pull_request:
  push:
    branches:
      - main
      - release-*
    tags-ignore: [ v.* ]
    # Different than its sibilings, we don't configure this workflow to run as a cron job.
    # The cron build compiles against Akka 2.6 and Akka HTTP 10.2, but the Maven example uses 2.5 and 10.1
    # see https://github.com/akka/akka-management/issues/744

jobs:
   integration-test:
    name: Integration Tests for Kubernetes API with Maven
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.21.0'
          driver: docker
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--addons=ingress'

      - name: Start docker
        run: |-
          ./integration-test/kubernetes-api-java/test.sh

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
