name: MiMa Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Check code formatted
        run: sbt +mimaReportBinaryIssues
