name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish-artifacts:
    name: Publish artifacts to Apache Nexus
    runs-on: ubuntu-20.04
    if: github.repository == 'apache/incubator-pekko-management'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Publish to Apache Maven repo
        run: sbt +publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
